spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trade
    username: root
    password: root@39
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  security:
    user:
      name: user
      password: password
  batch:
     jdbc:
       initialize-schema: always
     job:
       enabled: false
secret : CkdYNvPq2IxJtgFzL1QwvpF4IVv654rr433335555rer66464gggggs54646
expiration : 36000000
batch:
     path : C:\\Users\\sugur.balaji\\Desktop\\batchfile\\